== What is Komodo

Core of Komodo - Inversion of Control library and set of ready to use services like: configuration, module loading, etc. We're thinking about performance, maintainability and developer experience:

- performance – Komodo shouldn't affect compile or runtime performance, provide zero cost abstractions or best effort;
- maintainability – encourage best practices, clean and understandable code;
- developer experience – provide maximum value with minimal effort.

We heavily use Kotlin features, and doesn't care about Java users of framework. API for Java can be harder to use, but because of Kotlin interoperability Java developer should be able to use Komodo.

== When to Use?

We hope that framework will be ideal for small applications, microservices, web-servers. This is replacement for JavaEE webservers, microprofile, micro-frameworks and Spring Boot.

== Goals

. Simple: usage and internals;
. Fast: startup time;
. Testable: writing test should be easy just like writing code;
